name: Install Font in Workflow

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Copy Font to Local Fonts Directory
        run: |
          
          cp bb.ttf ~/.local/share/fonts

      - name: Refresh Font Cache
        run: |
          fc-cache -f -v  # Refresh font cache to make the font available
